include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"

linter:
  rules:
    # Dart Style
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_single_quotes: true

    # Code Quality
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_function_literals_in_foreach_calls: true
    avoid_types_on_closure_parameters: true

    # Performance
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true

    # Best Practices
    always_declare_return_types: true
    always_use_package_imports: true
    cancel_subscriptions: true
    close_sinks: true

    # Pub
    depend_on_referenced_packages: true
    package_names: true

    # Error Prevention
    unawaited_futures: true
    valid_regexps: true
