name: history_timeline
description: A Flutter application for exploring historical timelines

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # Routing
  go_router: ^13.0.0

  # UI & Icons
  cupertino_icons: ^1.0.2

  # HTTP (simplified)
  http: ^1.1.2

  # JSON & Data Models
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
