import 'package:history_timeline/core/models/country_data.dart';

class AppCountries {
  static const List<CountryData> allCountries = [
    // Africa
    CountryData(
      id: 'DZ',
      name: 'Algeria',
      code: 'DZ',
      latitude: 28.0339,
      longitude: 1.6596,
      continent: 'Africa',
    ),
    CountryData(
      id: 'AO',
      name: 'Angola',
      code: 'AO',
      latitude: -11.2027,
      longitude: 17.8739,
      continent: 'Africa',
    ),
    CountryData(
      id: 'BJ',
      name: 'Benin',
      code: 'BJ',
      latitude: 9.3077,
      longitude: 2.3158,
      continent: 'Africa',
    ),
    CountryData(
      id: 'BW',
      name: 'Botswana',
      code: 'BW',
      latitude: -22.3285,
      longitude: 24.6849,
      continent: 'Africa',
    ),
    CountryData(
      id: 'BF',
      name: 'Burkina Faso',
      code: 'BF',
      latitude: 12.2383,
      longitude: -1.5616,
      continent: 'Africa',
    ),
    CountryData(
      id: 'BI',
      name: 'Burundi',
      code: 'BI',
      latitude: -3.3731,
      longitude: 29.9189,
      continent: 'Africa',
    ),
    CountryData(
      id: 'CM',
      name: 'Cameroon',
      code: 'CM',
      latitude: 7.3697,
      longitude: 12.3547,
      continent: 'Africa',
    ),
    CountryData(
      id: 'CV',
      name: 'Cape Verde',
      code: 'CV',
      latitude: 16.5388,
      longitude: -24.0132,
      continent: 'Africa',
    ),
    CountryData(
      id: 'CF',
      name: 'Central African Republic',
      code: 'CF',
      latitude: 6.6111,
      longitude: 20.9394,
      continent: 'Africa',
    ),
    CountryData(
      id: 'TD',
      name: 'Chad',
      code: 'TD',
      latitude: 15.4542,
      longitude: 18.7322,
      continent: 'Africa',
    ),
    CountryData(
      id: 'KM',
      name: 'Comoros',
      code: 'KM',
      latitude: -11.6455,
      longitude: 43.3333,
      continent: 'Africa',
    ),
    CountryData(
      id: 'CG',
      name: 'Republic of the Congo',
      code: 'CG',
      latitude: -0.2280,
      longitude: 15.8277,
      continent: 'Africa',
    ),
    CountryData(
      id: 'CD',
      name: 'Democratic Republic of the Congo',
      code: 'CD',
      latitude: -4.0383,
      longitude: 21.7587,
      continent: 'Africa',
    ),
    CountryData(
      id: 'CI',
      name: 'Cote d\'Ivoire',
      code: 'CI',
      latitude: 7.5400,
      longitude: -5.5471,
      continent: 'Africa',
    ),
    CountryData(
      id: 'DJ',
      name: 'Djibouti',
      code: 'DJ',
      latitude: 11.8251,
      longitude: 42.5903,
      continent: 'Africa',
    ),
    CountryData(
      id: 'EG',
      name: 'Egypt',
      code: 'EG',
      latitude: 26.0975,
      longitude: 31.2357,
      continent: 'Africa',
    ),
    CountryData(
      id: 'GQ',
      name: 'Equatorial Guinea',
      code: 'GQ',
      latitude: 1.6508,
      longitude: 10.2679,
      continent: 'Africa',
    ),
    CountryData(
      id: 'ER',
      name: 'Eritrea',
      code: 'ER',
      latitude: 15.1794,
      longitude: 39.7823,
      continent: 'Africa',
    ),
    CountryData(
      id: 'ET',
      name: 'Ethiopia',
      code: 'ET',
      latitude: 9.1450,
      longitude: 40.4897,
      continent: 'Africa',
    ),
    CountryData(
      id: 'GA',
      name: 'Gabon',
      code: 'GA',
      latitude: -0.8037,
      longitude: 11.6094,
      continent: 'Africa',
    ),
    CountryData(
      id: 'GM',
      name: 'Gambia',
      code: 'GM',
      latitude: 13.4432,
      longitude: -15.3101,
      continent: 'Africa',
    ),
    CountryData(
      id: 'GH',
      name: 'Ghana',
      code: 'GH',
      latitude: 7.9465,
      longitude: -1.0232,
      continent: 'Africa',
    ),
    CountryData(
      id: 'GN',
      name: 'Guinea',
      code: 'GN',
      latitude: 9.9456,
      longitude: -9.6966,
      continent: 'Africa',
    ),
    CountryData(
      id: 'GW',
      name: 'Guinea-Bissau',
      code: 'GW',
      latitude: 11.8037,
      longitude: -15.1804,
      continent: 'Africa',
    ),
    CountryData(
      id: 'KE',
      name: 'Kenya',
      code: 'KE',
      latitude: -0.0236,
      longitude: 37.9062,
      continent: 'Africa',
    ),
    CountryData(
      id: 'LS',
      name: 'Lesotho',
      code: 'LS',
      latitude: -29.6100,
      longitude: 28.2336,
      continent: 'Africa',
    ),
    CountryData(
      id: 'LR',
      name: 'Liberia',
      code: 'LR',
      latitude: 6.4281,
      longitude: -9.4295,
      continent: 'Africa',
    ),
    CountryData(
      id: 'LY',
      name: 'Libya',
      code: 'LY',
      latitude: 26.3351,
      longitude: 17.2283,
      continent: 'Africa',
    ),
    CountryData(
      id: 'MG',
      name: 'Madagascar',
      code: 'MG',
      latitude: -18.7669,
      longitude: 46.8691,
      continent: 'Africa',
    ),
    CountryData(
      id: 'MW',
      name: 'Malawi',
      code: 'MW',
      latitude: -13.2543,
      longitude: 34.3015,
      continent: 'Africa',
    ),
    CountryData(
      id: 'ML',
      name: 'Mali',
      code: 'ML',
      latitude: 17.5707,
      longitude: -3.9962,
      continent: 'Africa',
    ),
    CountryData(
      id: 'MR',
      name: 'Mauritania',
      code: 'MR',
      latitude: 21.0079,
      longitude: -10.9408,
      continent: 'Africa',
    ),
    CountryData(
      id: 'MU',
      name: 'Mauritius',
      code: 'MU',
      latitude: -20.3484,
      longitude: 57.5522,
      continent: 'Africa',
    ),
    CountryData(
      id: 'MA',
      name: 'Morocco',
      code: 'MA',
      latitude: 31.7917,
      longitude: -7.0926,
      continent: 'Africa',
    ),
    CountryData(
      id: 'MZ',
      name: 'Mozambique',
      code: 'MZ',
      latitude: -18.6657,
      longitude: 35.5296,
      continent: 'Africa',
    ),
    CountryData(
      id: 'NA',
      name: 'Namibia',
      code: 'NA',
      latitude: -22.9576,
      longitude: 18.4904,
      continent: 'Africa',
    ),
    CountryData(
      id: 'NE',
      name: 'Niger',
      code: 'NE',
      latitude: 17.6078,
      longitude: 8.0817,
      continent: 'Africa',
    ),
    CountryData(
      id: 'NG',
      name: 'Nigeria',
      code: 'NG',
      latitude: 9.0820,
      longitude: 8.6753,
      continent: 'Africa',
    ),
    CountryData(
      id: 'RW',
      name: 'Rwanda',
      code: 'RW',
      latitude: -1.9403,
      longitude: 29.8739,
      continent: 'Africa',
    ),
    CountryData(
      id: 'ST',
      name: 'Sao Tome and Principe',
      code: 'ST',
      latitude: 0.1864,
      longitude: 6.6131,
      continent: 'Africa',
    ),
    CountryData(
      id: 'SN',
      name: 'Senegal',
      code: 'SN',
      latitude: 14.4974,
      longitude: -14.4524,
      continent: 'Africa',
    ),
    CountryData(
      id: 'SC',
      name: 'Seychelles',
      code: 'SC',
      latitude: -4.6796,
      longitude: 55.4920,
      continent: 'Africa',
    ),
    CountryData(
      id: 'SL',
      name: 'Sierra Leone',
      code: 'SL',
      latitude: 8.4606,
      longitude: -11.7799,
      continent: 'Africa',
    ),
    CountryData(
      id: 'SO',
      name: 'Somalia',
      code: 'SO',
      latitude: 5.1521,
      longitude: 46.1996,
      continent: 'Africa',
    ),
    CountryData(
      id: 'ZA',
      name: 'South Africa',
      code: 'ZA',
      latitude: -30.5595,
      longitude: 22.9375,
      continent: 'Africa',
    ),
    CountryData(
      id: 'SS',
      name: 'South Sudan',
      code: 'SS',
      latitude: 6.8770,
      longitude: 31.3070,
      continent: 'Africa',
    ),
    CountryData(
      id: 'SD',
      name: 'Sudan',
      code: 'SD',
      latitude: 12.8628,
      longitude: 30.2176,
      continent: 'Africa',
    ),
    CountryData(
      id: 'SZ',
      name: 'Eswatini',
      code: 'SZ',
      latitude: -26.5225,
      longitude: 31.4659,
      continent: 'Africa',
    ),
    CountryData(
      id: 'TZ',
      name: 'Tanzania',
      code: 'TZ',
      latitude: -6.3690,
      longitude: 34.8888,
      continent: 'Africa',
    ),
    CountryData(
      id: 'TG',
      name: 'Togo',
      code: 'TG',
      latitude: 8.6195,
      longitude: 0.8248,
      continent: 'Africa',
    ),
    CountryData(
      id: 'TN',
      name: 'Tunisia',
      code: 'TN',
      latitude: 33.8869,
      longitude: 9.5375,
      continent: 'Africa',
    ),
    CountryData(
      id: 'UG',
      name: 'Uganda',
      code: 'UG',
      latitude: 1.3733,
      longitude: 32.2903,
      continent: 'Africa',
    ),
    CountryData(
      id: 'ZM',
      name: 'Zambia',
      code: 'ZM',
      latitude: -13.1339,
      longitude: 27.8493,
      continent: 'Africa',
    ),
    CountryData(
      id: 'ZW',
      name: 'Zimbabwe',
      code: 'ZW',
      latitude: -19.0154,
      longitude: 29.1549,
      continent: 'Africa',
    ),

    // Asia
    CountryData(
      id: 'AF',
      name: 'Afghanistan',
      code: 'AF',
      latitude: 33.9391,
      longitude: 67.7100,
      continent: 'Asia',
    ),
    CountryData(
      id: 'AM',
      name: 'Armenia',
      code: 'AM',
      latitude: 40.0691,
      longitude: 45.0382,
      continent: 'Asia',
    ),
    CountryData(
      id: 'AZ',
      name: 'Azerbaijan',
      code: 'AZ',
      latitude: 40.1431,
      longitude: 47.5769,
      continent: 'Asia',
    ),
    CountryData(
      id: 'BH',
      name: 'Bahrain',
      code: 'BH',
      latitude: 25.9304,
      longitude: 50.6378,
      continent: 'Asia',
    ),
    CountryData(
      id: 'BD',
      name: 'Bangladesh',
      code: 'BD',
      latitude: 23.6850,
      longitude: 90.3563,
      continent: 'Asia',
    ),
    CountryData(
      id: 'BT',
      name: 'Bhutan',
      code: 'BT',
      latitude: 27.5142,
      longitude: 90.4336,
      continent: 'Asia',
    ),
    CountryData(
      id: 'BN',
      name: 'Brunei',
      code: 'BN',
      latitude: 4.5353,
      longitude: 114.7277,
      continent: 'Asia',
    ),
    CountryData(
      id: 'KH',
      name: 'Cambodia',
      code: 'KH',
      latitude: 12.5657,
      longitude: 104.9910,
      continent: 'Asia',
    ),
    CountryData(
      id: 'CN',
      name: 'China',
      code: 'CN',
      latitude: 35.8617,
      longitude: 104.1954,
      continent: 'Asia',
    ),
    CountryData(
      id: 'CY',
      name: 'Cyprus',
      code: 'CY',
      latitude: 35.1264,
      longitude: 33.4299,
      continent: 'Asia',
    ),
    CountryData(
      id: 'GE',
      name: 'Georgia',
      code: 'GE',
      latitude: 42.3154,
      longitude: 43.3569,
      continent: 'Asia',
    ),
    CountryData(
      id: 'IN',
      name: 'India',
      code: 'IN',
      latitude: 20.5937,
      longitude: 78.9629,
      continent: 'Asia',
    ),
    CountryData(
      id: 'ID',
      name: 'Indonesia',
      code: 'ID',
      latitude: -0.7893,
      longitude: 113.9213,
      continent: 'Asia',
    ),
    CountryData(
      id: 'IR',
      name: 'Iran',
      code: 'IR',
      latitude: 32.4279,
      longitude: 53.6880,
      continent: 'Asia',
    ),
    CountryData(
      id: 'IQ',
      name: 'Iraq',
      code: 'IQ',
      latitude: 33.2232,
      longitude: 43.6793,
      continent: 'Asia',
    ),
    CountryData(
      id: 'IL',
      name: 'Israel',
      code: 'IL',
      latitude: 31.0461,
      longitude: 34.8516,
      continent: 'Asia',
    ),
    CountryData(
      id: 'JP',
      name: 'Japan',
      code: 'JP',
      latitude: 36.2048,
      longitude: 138.2529,
      continent: 'Asia',
    ),
    CountryData(
      id: 'JO',
      name: 'Jordan',
      code: 'JO',
      latitude: 30.5852,
      longitude: 36.2384,
      continent: 'Asia',
    ),
    CountryData(
      id: 'KZ',
      name: 'Kazakhstan',
      code: 'KZ',
      latitude: 48.0196,
      longitude: 66.9237,
      continent: 'Asia',
    ),
    CountryData(
      id: 'KW',
      name: 'Kuwait',
      code: 'KW',
      latitude: 29.3117,
      longitude: 47.4818,
      continent: 'Asia',
    ),
    CountryData(
      id: 'KG',
      name: 'Kyrgyzstan',
      code: 'KG',
      latitude: 41.2044,
      longitude: 74.7661,
      continent: 'Asia',
    ),
    CountryData(
      id: 'LA',
      name: 'Laos',
      code: 'LA',
      latitude: 19.8563,
      longitude: 102.4955,
      continent: 'Asia',
    ),
    CountryData(
      id: 'LB',
      name: 'Lebanon',
      code: 'LB',
      latitude: 33.8547,
      longitude: 35.8623,
      continent: 'Asia',
    ),
    CountryData(
      id: 'MY',
      name: 'Malaysia',
      code: 'MY',
      latitude: 4.2105,
      longitude: 101.9758,
      continent: 'Asia',
    ),
    CountryData(
      id: 'MV',
      name: 'Maldives',
      code: 'MV',
      latitude: 3.2028,
      longitude: 73.2207,
      continent: 'Asia',
    ),
    CountryData(
      id: 'MN',
      name: 'Mongolia',
      code: 'MN',
      latitude: 46.8625,
      longitude: 103.8467,
      continent: 'Asia',
    ),
    CountryData(
      id: 'MM',
      name: 'Myanmar',
      code: 'MM',
      latitude: 21.9162,
      longitude: 95.9560,
      continent: 'Asia',
    ),
    CountryData(
      id: 'NP',
      name: 'Nepal',
      code: 'NP',
      latitude: 28.3949,
      longitude: 84.1240,
      continent: 'Asia',
    ),
    CountryData(
      id: 'KP',
      name: 'North Korea',
      code: 'KP',
      latitude: 40.3399,
      longitude: 127.5101,
      continent: 'Asia',
    ),
    CountryData(
      id: 'OM',
      name: 'Oman',
      code: 'OM',
      latitude: 21.4735,
      longitude: 55.9754,
      continent: 'Asia',
    ),
    CountryData(
      id: 'PK',
      name: 'Pakistan',
      code: 'PK',
      latitude: 30.3753,
      longitude: 69.3451,
      continent: 'Asia',
    ),
    CountryData(
      id: 'PS',
      name: 'Palestine',
      code: 'PS',
      latitude: 31.9522,
      longitude: 35.2332,
      continent: 'Asia',
    ),
    CountryData(
      id: 'PH',
      name: 'Philippines',
      code: 'PH',
      latitude: 12.8797,
      longitude: 121.7740,
      continent: 'Asia',
    ),
    CountryData(
      id: 'QA',
      name: 'Qatar',
      code: 'QA',
      latitude: 25.3548,
      longitude: 51.1839,
      continent: 'Asia',
    ),
    CountryData(
      id: 'RU',
      name: 'Russia',
      code: 'RU',
      latitude: 61.5240,
      longitude: 105.3188,
      continent: 'Asia',
    ),
    CountryData(
      id: 'SA',
      name: 'Saudi Arabia',
      code: 'SA',
      latitude: 23.8859,
      longitude: 45.0792,
      continent: 'Asia',
    ),
    CountryData(
      id: 'SG',
      name: 'Singapore',
      code: 'SG',
      latitude: 1.3521,
      longitude: 103.8198,
      continent: 'Asia',
    ),
    CountryData(
      id: 'KR',
      name: 'South Korea',
      code: 'KR',
      latitude: 35.9078,
      longitude: 127.7669,
      continent: 'Asia',
    ),
    CountryData(
      id: 'LK',
      name: 'Sri Lanka',
      code: 'LK',
      latitude: 7.8731,
      longitude: 80.7718,
      continent: 'Asia',
    ),
    CountryData(
      id: 'SY',
      name: 'Syria',
      code: 'SY',
      latitude: 34.8021,
      longitude: 38.9968,
      continent: 'Asia',
    ),
    CountryData(
      id: 'TW',
      name: 'Taiwan',
      code: 'TW',
      latitude: 23.6978,
      longitude: 120.9605,
      continent: 'Asia',
    ),
    CountryData(
      id: 'TJ',
      name: 'Tajikistan',
      code: 'TJ',
      latitude: 38.8610,
      longitude: 71.2761,
      continent: 'Asia',
    ),
    CountryData(
      id: 'TH',
      name: 'Thailand',
      code: 'TH',
      latitude: 15.8700,
      longitude: 100.9925,
      continent: 'Asia',
    ),
    CountryData(
      id: 'TL',
      name: 'Timor-Leste',
      code: 'TL',
      latitude: -8.8742,
      longitude: 125.7275,
      continent: 'Asia',
    ),
    CountryData(
      id: 'TR',
      name: 'Turkey',
      code: 'TR',
      latitude: 38.9637,
      longitude: 35.2433,
      continent: 'Asia',
    ),
    CountryData(
      id: 'TM',
      name: 'Turkmenistan',
      code: 'TM',
      latitude: 38.9697,
      longitude: 59.5563,
      continent: 'Asia',
    ),
    CountryData(
      id: 'AE',
      name: 'United Arab Emirates',
      code: 'AE',
      latitude: 23.4241,
      longitude: 53.8478,
      continent: 'Asia',
    ),
    CountryData(
      id: 'UZ',
      name: 'Uzbekistan',
      code: 'UZ',
      latitude: 41.3775,
      longitude: 64.5853,
      continent: 'Asia',
    ),
    CountryData(
      id: 'VN',
      name: 'Vietnam',
      code: 'VN',
      latitude: 14.0583,
      longitude: 108.2772,
      continent: 'Asia',
    ),
    CountryData(
      id: 'YE',
      name: 'Yemen',
      code: 'YE',
      latitude: 15.5527,
      longitude: 48.5164,
      continent: 'Asia',
    ),

    // Europe
    CountryData(
      id: 'AL',
      name: 'Albania',
      code: 'AL',
      latitude: 41.1533,
      longitude: 20.1683,
      continent: 'Europe',
    ),
    CountryData(
      id: 'AD',
      name: 'Andorra',
      code: 'AD',
      latitude: 42.5462,
      longitude: 1.6016,
      continent: 'Europe',
    ),
    CountryData(
      id: 'AT',
      name: 'Austria',
      code: 'AT',
      latitude: 47.5162,
      longitude: 14.5501,
      continent: 'Europe',
    ),
    CountryData(
      id: 'BY',
      name: 'Belarus',
      code: 'BY',
      latitude: 53.7098,
      longitude: 27.9534,
      continent: 'Europe',
    ),
    CountryData(
      id: 'BE',
      name: 'Belgium',
      code: 'BE',
      latitude: 50.5039,
      longitude: 4.4699,
      continent: 'Europe',
    ),
    CountryData(
      id: 'BA',
      name: 'Bosnia and Herzegovina',
      code: 'BA',
      latitude: 43.9159,
      longitude: 17.6791,
      continent: 'Europe',
    ),
    CountryData(
      id: 'BG',
      name: 'Bulgaria',
      code: 'BG',
      latitude: 42.7339,
      longitude: 25.4858,
      continent: 'Europe',
    ),
    CountryData(
      id: 'HR',
      name: 'Croatia',
      code: 'HR',
      latitude: 45.1000,
      longitude: 15.2000,
      continent: 'Europe',
    ),
    CountryData(
      id: 'CZ',
      name: 'Czech Republic',
      code: 'CZ',
      latitude: 49.8175,
      longitude: 15.4730,
      continent: 'Europe',
    ),
    CountryData(
      id: 'DK',
      name: 'Denmark',
      code: 'DK',
      latitude: 56.2639,
      longitude: 9.5018,
      continent: 'Europe',
    ),
    CountryData(
      id: 'EE',
      name: 'Estonia',
      code: 'EE',
      latitude: 58.5953,
      longitude: 25.0136,
      continent: 'Europe',
    ),
    CountryData(
      id: 'FI',
      name: 'Finland',
      code: 'FI',
      latitude: 61.9241,
      longitude: 25.7482,
      continent: 'Europe',
    ),
    CountryData(
      id: 'FR',
      name: 'France',
      code: 'FR',
      latitude: 46.2276,
      longitude: 2.2137,
      continent: 'Europe',
    ),
    CountryData(
      id: 'DE',
      name: 'Germany',
      code: 'DE',
      latitude: 51.1657,
      longitude: 10.4515,
      continent: 'Europe',
    ),
    CountryData(
      id: 'GR',
      name: 'Greece',
      code: 'GR',
      latitude: 39.0742,
      longitude: 21.8243,
      continent: 'Europe',
    ),
    CountryData(
      id: 'HU',
      name: 'Hungary',
      code: 'HU',
      latitude: 47.1625,
      longitude: 19.5033,
      continent: 'Europe',
    ),
    CountryData(
      id: 'IS',
      name: 'Iceland',
      code: 'IS',
      latitude: 64.9631,
      longitude: -19.0208,
      continent: 'Europe',
    ),
    CountryData(
      id: 'IE',
      name: 'Ireland',
      code: 'IE',
      latitude: 53.4129,
      longitude: -8.2439,
      continent: 'Europe',
    ),
    CountryData(
      id: 'IT',
      name: 'Italy',
      code: 'IT',
      latitude: 41.8719,
      longitude: 12.5674,
      continent: 'Europe',
    ),
    CountryData(
      id: 'LV',
      name: 'Latvia',
      code: 'LV',
      latitude: 56.8796,
      longitude: 24.6032,
      continent: 'Europe',
    ),
    CountryData(
      id: 'LI',
      name: 'Liechtenstein',
      code: 'LI',
      latitude: 47.1660,
      longitude: 9.5554,
      continent: 'Europe',
    ),
    CountryData(
      id: 'LT',
      name: 'Lithuania',
      code: 'LT',
      latitude: 55.1694,
      longitude: 23.8813,
      continent: 'Europe',
    ),
    CountryData(
      id: 'LU',
      name: 'Luxembourg',
      code: 'LU',
      latitude: 49.8153,
      longitude: 6.1296,
      continent: 'Europe',
    ),
    CountryData(
      id: 'MT',
      name: 'Malta',
      code: 'MT',
      latitude: 35.9375,
      longitude: 14.3754,
      continent: 'Europe',
    ),
    CountryData(
      id: 'MD',
      name: 'Moldova',
      code: 'MD',
      latitude: 47.4116,
      longitude: 28.3699,
      continent: 'Europe',
    ),
    CountryData(
      id: 'MC',
      name: 'Monaco',
      code: 'MC',
      latitude: 43.7384,
      longitude: 7.4246,
      continent: 'Europe',
    ),
    CountryData(
      id: 'ME',
      name: 'Montenegro',
      code: 'ME',
      latitude: 42.7087,
      longitude: 19.3744,
      continent: 'Europe',
    ),
    CountryData(
      id: 'NL',
      name: 'Netherlands',
      code: 'NL',
      latitude: 52.1326,
      longitude: 5.2913,
      continent: 'Europe',
    ),
    CountryData(
      id: 'MK',
      name: 'North Macedonia',
      code: 'MK',
      latitude: 41.6086,
      longitude: 21.7453,
      continent: 'Europe',
    ),
    CountryData(
      id: 'NO',
      name: 'Norway',
      code: 'NO',
      latitude: 60.4720,
      longitude: 8.4689,
      continent: 'Europe',
    ),
    CountryData(
      id: 'PL',
      name: 'Poland',
      code: 'PL',
      latitude: 51.9194,
      longitude: 19.1451,
      continent: 'Europe',
    ),
    CountryData(
      id: 'PT',
      name: 'Portugal',
      code: 'PT',
      latitude: 39.3999,
      longitude: -8.2245,
      continent: 'Europe',
    ),
    CountryData(
      id: 'RO',
      name: 'Romania',
      code: 'RO',
      latitude: 45.9432,
      longitude: 24.9668,
      continent: 'Europe',
    ),
    CountryData(
      id: 'SM',
      name: 'San Marino',
      code: 'SM',
      latitude: 43.9424,
      longitude: 12.4578,
      continent: 'Europe',
    ),
    CountryData(
      id: 'RS',
      name: 'Serbia',
      code: 'RS',
      latitude: 44.0165,
      longitude: 21.0059,
      continent: 'Europe',
    ),
    CountryData(
      id: 'SK',
      name: 'Slovakia',
      code: 'SK',
      latitude: 48.6690,
      longitude: 19.6990,
      continent: 'Europe',
    ),
    CountryData(
      id: 'SI',
      name: 'Slovenia',
      code: 'SI',
      latitude: 46.1512,
      longitude: 14.9955,
      continent: 'Europe',
    ),
    CountryData(
      id: 'ES',
      name: 'Spain',
      code: 'ES',
      latitude: 40.4637,
      longitude: -3.7492,
      continent: 'Europe',
    ),
    CountryData(
      id: 'SE',
      name: 'Sweden',
      code: 'SE',
      latitude: 60.1282,
      longitude: 18.6435,
      continent: 'Europe',
    ),
    CountryData(
      id: 'CH',
      name: 'Switzerland',
      code: 'CH',
      latitude: 46.8182,
      longitude: 8.2275,
      continent: 'Europe',
    ),
    CountryData(
      id: 'UA',
      name: 'Ukraine',
      code: 'UA',
      latitude: 48.3794,
      longitude: 31.1656,
      continent: 'Europe',
    ),
    CountryData(
      id: 'GB',
      name: 'United Kingdom',
      code: 'GB',
      latitude: 55.3781,
      longitude: -3.4360,
      continent: 'Europe',
    ),
    CountryData(
      id: 'VA',
      name: 'Vatican City',
      code: 'VA',
      latitude: 41.9029,
      longitude: 12.4534,
      continent: 'Europe',
    ),

    // North America
    CountryData(
      id: 'AG',
      name: 'Antigua and Barbuda',
      code: 'AG',
      latitude: 17.0608,
      longitude: -61.7964,
      continent: 'North America',
    ),
    CountryData(
      id: 'BS',
      name: 'Bahamas',
      code: 'BS',
      latitude: 25.0343,
      longitude: -77.3963,
      continent: 'North America',
    ),
    CountryData(
      id: 'BB',
      name: 'Barbados',
      code: 'BB',
      latitude: 13.1939,
      longitude: -59.5432,
      continent: 'North America',
    ),
    CountryData(
      id: 'BZ',
      name: 'Belize',
      code: 'BZ',
      latitude: 17.1899,
      longitude: -88.4976,
      continent: 'North America',
    ),
    CountryData(
      id: 'CA',
      name: 'Canada',
      code: 'CA',
      latitude: 56.1304,
      longitude: -106.3468,
      continent: 'North America',
    ),
    CountryData(
      id: 'CR',
      name: 'Costa Rica',
      code: 'CR',
      latitude: 9.7489,
      longitude: -83.7534,
      continent: 'North America',
    ),
    CountryData(
      id: 'CU',
      name: 'Cuba',
      code: 'CU',
      latitude: 21.5218,
      longitude: -77.7812,
      continent: 'North America',
    ),
    CountryData(
      id: 'DM',
      name: 'Dominica',
      code: 'DM',
      latitude: 15.4150,
      longitude: -61.3710,
      continent: 'North America',
    ),
    CountryData(
      id: 'DO',
      name: 'Dominican Republic',
      code: 'DO',
      latitude: 18.7357,
      longitude: -70.1627,
      continent: 'North America',
    ),
    CountryData(
      id: 'SV',
      name: 'El Salvador',
      code: 'SV',
      latitude: 13.7942,
      longitude: -88.8965,
      continent: 'North America',
    ),
    CountryData(
      id: 'GD',
      name: 'Grenada',
      code: 'GD',
      latitude: 12.1165,
      longitude: -61.6790,
      continent: 'North America',
    ),
    CountryData(
      id: 'GT',
      name: 'Guatemala',
      code: 'GT',
      latitude: 15.7835,
      longitude: -90.2308,
      continent: 'North America',
    ),
    CountryData(
      id: 'HT',
      name: 'Haiti',
      code: 'HT',
      latitude: 18.9712,
      longitude: -72.2852,
      continent: 'North America',
    ),
    CountryData(
      id: 'HN',
      name: 'Honduras',
      code: 'HN',
      latitude: 15.2000,
      longitude: -86.2419,
      continent: 'North America',
    ),
    CountryData(
      id: 'JM',
      name: 'Jamaica',
      code: 'JM',
      latitude: 18.1096,
      longitude: -77.2975,
      continent: 'North America',
    ),
    CountryData(
      id: 'MX',
      name: 'Mexico',
      code: 'MX',
      latitude: 23.6345,
      longitude: -102.5528,
      continent: 'North America',
    ),
    CountryData(
      id: 'NI',
      name: 'Nicaragua',
      code: 'NI',
      latitude: 12.2651,
      longitude: -85.2072,
      continent: 'North America',
    ),
    CountryData(
      id: 'PA',
      name: 'Panama',
      code: 'PA',
      latitude: 8.5380,
      longitude: -80.7821,
      continent: 'North America',
    ),
    CountryData(
      id: 'KN',
      name: 'Saint Kitts and Nevis',
      code: 'KN',
      latitude: 17.3578,
      longitude: -62.7830,
      continent: 'North America',
    ),
    CountryData(
      id: 'LC',
      name: 'Saint Lucia',
      code: 'LC',
      latitude: 13.9094,
      longitude: -60.9789,
      continent: 'North America',
    ),
    CountryData(
      id: 'VC',
      name: 'Saint Vincent and the Grenadines',
      code: 'VC',
      latitude: 12.9843,
      longitude: -61.2872,
      continent: 'North America',
    ),
    CountryData(
      id: 'TT',
      name: 'Trinidad and Tobago',
      code: 'TT',
      latitude: 10.6918,
      longitude: -61.2225,
      continent: 'North America',
    ),
    CountryData(
      id: 'US',
      name: 'United States',
      code: 'US',
      latitude: 37.0902,
      longitude: -95.7129,
      continent: 'North America',
    ),

    // South America
    CountryData(
      id: 'AR',
      name: 'Argentina',
      code: 'AR',
      latitude: -38.4161,
      longitude: -63.6167,
      continent: 'South America',
    ),
    CountryData(
      id: 'BO',
      name: 'Bolivia',
      code: 'BO',
      latitude: -16.2902,
      longitude: -63.5887,
      continent: 'South America',
    ),
    CountryData(
      id: 'BR',
      name: 'Brazil',
      code: 'BR',
      latitude: -14.2350,
      longitude: -51.9253,
      continent: 'South America',
    ),
    CountryData(
      id: 'CL',
      name: 'Chile',
      code: 'CL',
      latitude: -35.6751,
      longitude: -71.5430,
      continent: 'South America',
    ),
    CountryData(
      id: 'CO',
      name: 'Colombia',
      code: 'CO',
      latitude: 4.5709,
      longitude: -74.2973,
      continent: 'South America',
    ),
    CountryData(
      id: 'EC',
      name: 'Ecuador',
      code: 'EC',
      latitude: -1.8312,
      longitude: -78.1834,
      continent: 'South America',
    ),
    CountryData(
      id: 'GY',
      name: 'Guyana',
      code: 'GY',
      latitude: 4.8604,
      longitude: -58.9302,
      continent: 'South America',
    ),
    CountryData(
      id: 'PY',
      name: 'Paraguay',
      code: 'PY',
      latitude: -23.4425,
      longitude: -58.4438,
      continent: 'South America',
    ),
    CountryData(
      id: 'PE',
      name: 'Peru',
      code: 'PE',
      latitude: -9.1900,
      longitude: -75.0152,
      continent: 'South America',
    ),
    CountryData(
      id: 'SR',
      name: 'Suriname',
      code: 'SR',
      latitude: 3.9193,
      longitude: -56.0278,
      continent: 'South America',
    ),
    CountryData(
      id: 'UY',
      name: 'Uruguay',
      code: 'UY',
      latitude: -32.5228,
      longitude: -55.7658,
      continent: 'South America',
    ),
    CountryData(
      id: 'VE',
      name: 'Venezuela',
      code: 'VE',
      latitude: 6.4238,
      longitude: -66.5897,
      continent: 'South America',
    ),

    // Oceania
    CountryData(
      id: 'AU',
      name: 'Australia',
      code: 'AU',
      latitude: -25.2744,
      longitude: 133.7751,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'FJ',
      name: 'Fiji',
      code: 'FJ',
      latitude: -16.5780,
      longitude: 179.4144,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'KI',
      name: 'Kiribati',
      code: 'KI',
      latitude: -3.3704,
      longitude: -168.7340,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'MH',
      name: 'Marshall Islands',
      code: 'MH',
      latitude: 7.1315,
      longitude: 171.1845,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'FM',
      name: 'Micronesia',
      code: 'FM',
      latitude: 7.4256,
      longitude: 150.5508,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'NR',
      name: 'Nauru',
      code: 'NR',
      latitude: -0.5228,
      longitude: 166.9315,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'NZ',
      name: 'New Zealand',
      code: 'NZ',
      latitude: -40.9006,
      longitude: 174.8860,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'PW',
      name: 'Palau',
      code: 'PW',
      latitude: 7.5150,
      longitude: 134.5825,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'PG',
      name: 'Papua New Guinea',
      code: 'PG',
      latitude: -6.3150,
      longitude: 143.9555,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'WS',
      name: 'Samoa',
      code: 'WS',
      latitude: -13.7590,
      longitude: -172.1046,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'SB',
      name: 'Solomon Islands',
      code: 'SB',
      latitude: -9.6457,
      longitude: 160.1562,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'TO',
      name: 'Tonga',
      code: 'TO',
      latitude: -21.1789,
      longitude: -175.1982,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'TV',
      name: 'Tuvalu',
      code: 'TV',
      latitude: -7.1095,
      longitude: 177.6493,
      continent: 'Oceania',
    ),
    CountryData(
      id: 'VU',
      name: 'Vanuatu',
      code: 'VU',
      latitude: -15.3767,
      longitude: 166.9592,
      continent: 'Oceania',
    ),
  ];

  /// Get countries by continent
  static List<CountryData> getByContinent(String continent) {
    return allCountries
        .where((country) => country.continent == continent)
        .toList();
  }

  /// Get country by ID
  static CountryData? getById(String id) {
    try {
      return allCountries.firstWhere((country) => country.id == id);
    } catch (e) {
      return null;
    }
  }

  /// Get all continents
  static List<String> getAllContinents() {
    return allCountries.map((country) => country.continent).toSet().toList()
      ..sort();
  }
}
